name: euda_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.1+51

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  get: ^4.3.8
  provider: ^6.0.1
  http: ^0.13.1
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  fl_chart: ^0.41.0
  # syncfusion_flutter_charts: ^19.4.38
  # package_info_plus: ^1.3.0
  # firebase_messaging: ^11.1.0
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.1.2
  firebase_core: ^1.10.0
  
  # audioplayers: ^1.1.1
  # audioplayers: ^0.20.1
  just_audio: ^0.9.31
  audio_service: ^0.18.9
  url_launcher: ^6.0.17

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  video_player: ^2.2.10
  chewie: ^1.2.2
  
  flutter_svg: ^1.0.2
  add_2_calendar: ^2.1.2
  flutter_markdown: ^0.6.9
  fluttertoast: ^8.0.8
  flutter_inappwebview: ^5.3.2
  
  carousel_slider: ^4.1.1
  firebase_remote_config: ^2.0.20
  uuid: ^3.0.7

dependency_overrides:
  provider: ^6.0.1
  platform: ^3.1.0
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
# The following section is specific to Flutter.
flutter:
  assets:

  - assets/images/splash.svg
  # - assets/images/splash.jpg
  - assets/images/euda_splash.gif
  - assets/images/dashboard_bg.png
  - assets/images/white_bg.png
  # - assets/images/cinema.jpeg
  # - assets/images/events.jpeg
  # - assets/images/meditation.jpeg
  # - assets/images/myhistory.jpeg
  # - assets/images/resources.jpeg
  # - assets/images/supportLink.jpeg  
  # - assets/images/learning.jpg  

  - assets/icons/home/Notification_bell_new.svg
  - assets/icons/home/Notification_bell.svg

  - assets/icons/profile/EditProfile.svg
  - assets/icons/profile/HelpCenter.svg
  - assets/icons/profile/LogOut.svg
  - assets/icons/profile/TermsAndConditions.svg
  - assets/icons/profile/UserInformation.svg
  - assets/icons/profile/Notification.svg
  
  - assets/icons/bottom_nav/CheckIn.png
  # - assets/icons/bottom_nav/Home_Actrive.png
  # - assets/icons/bottom_nav/Home_InActrive.png
  # - assets/icons/bottom_nav/Plugins_Actrive.png
  # - assets/icons/bottom_nav/Plugins_InActrive.png
  # - assets/icons/bottom_nav/Profile_Actrive.png
  # - assets/icons/bottom_nav/Profile_InActrive.png
  # - assets/icons/bottom_nav/Settings_Actrive.png
  # - assets/icons/bottom_nav/Settings_InActrive.png

  - assets/icons/bottom_nav/Home_Active.svg
  - assets/icons/bottom_nav/Home_InActive.svg
  - assets/icons/bottom_nav/Plugins_Active.svg
  - assets/icons/bottom_nav/Plugins_InActive.svg
  - assets/icons/bottom_nav/Profile_Active.svg
  - assets/icons/bottom_nav/Profile_InActive.svg
  - assets/icons/bottom_nav/Settings_Active.svg
  - assets/icons/bottom_nav/Settings_InActive.svg
  - assets/icons/bottom_nav/Meditate_Active.svg
  - assets/icons/bottom_nav/Meditate_InActive.svg
  

  - assets/icons/search/search.png
  - assets/icons/search/search.png
  - assets/icons/search/Search.svg
  - assets/icons/search/filter.svg
  - assets/icons/meditation/clock.png

  - assets/icons/modals/Star_Active.svg
  - assets/icons/modals/Star_InActive.svg
  - assets/icons/modals/Star_Active.png
  - assets/icons/modals/Star_InActive.png


  ##Background
  - assets/images/Euda-Cinema.png
  - assets/images/Euda-Events.png
  - assets/images/Euda-MyHistory.png
  - assets/images/Euda-Resources.png
  - assets/images/Euda-Support.png
  - assets/images/Euda-Course.png



  # - assets/icons/plugins/Cinema.svg
  # - assets/icons/plugins/Events.svg
  # - assets/icons/plugins/Meditations.svg
  # - assets/icons/plugins/MyHistory.svg
  - assets/icons/plugins/MyHistoryGreen.svg
  # - assets/icons/plugins/Resources.svg
  # - assets/icons/plugins/Support.svg

  - assets/icons/shared/circle.svg
  - assets/icons/shared/circle_check.svg
  - assets/icons/shared/back_arrow.svg
  - assets/icons/shared/back_arrow_white.svg
  - assets/icons/shared/back_arrow.png
  - assets/icons/shared/Play.png
  - assets/icons/shared/CloseButton.svg
  - assets/icons/shared/Checkin.svg

  - assets/icons/shared/ActiveCheckbox.svg
  - assets/icons/shared/InActiveCheckbox.svg

  - assets/icons/meditation/Play.svg
  - assets/icons/meditation/Play.svg


  - assets/icons/meditation/Play.svg
  - assets/icons/meditation/Back15.png
  - assets/icons/meditation/Next15.png
  - assets/icons/meditation/Pause.png
  - assets/icons/meditation/Pause.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: google_fonts/Manrope-Bold.ttf
        - asset: google_fonts/Manrope-ExtraBold.ttf
        - asset: google_fonts/Manrope-ExtraLight.ttf
        - asset: google_fonts/Manrope-Light.ttf
        - asset: google_fonts/Manrope-Medium.ttf
        - asset: google_fonts/Manrope-SemiBold.ttf
        - asset: google_fonts/Manrope-Regular.ttf
    - family: Barlow-bold
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf

    - family: Barlow-regular
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
        
    - family: Barlow-light
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
