name: audio_player
description: A new Flutter project..
publish_to: 'none' 
version: 1.5.1+51

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.3.8
  just_audio: ^0.9.31
  audio_service: ^0.18.9
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7

dependency_overrides:
  platform: ^3.1.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
